export type PermissionDefinition = {
  code: string;
  name: string;
  module: string;
  resource: string;
  action: string;
  description?: string;
};

const permission = (
  code: string,
  name: string,
  module: string,
  resource: string,
  action: string,
  description?: string,
): PermissionDefinition => ({
  code,
  name,
  module,
  resource,
  action,
  description,
});

export const PERMISSIONS: PermissionDefinition[] = [
  permission('dashboard.view', 'Visualizar dashboard', 'Dashboard', 'Dashboard', 'view'),

  permission('atendimentos.appointments.view', 'Ver agendamentos', 'Atendimentos', 'Agendamentos', 'view'),
  permission('atendimentos.appointments.create', 'Criar agendamentos', 'Atendimentos', 'Agendamentos', 'create'),
  permission('atendimentos.appointments.update', 'Editar agendamentos', 'Atendimentos', 'Agendamentos', 'update'),
  permission('atendimentos.appointments.cancel', 'Cancelar agendamentos', 'Atendimentos', 'Agendamentos', 'cancel'),
  permission('atendimentos.appointments.confirm', 'Confirmar agendamentos', 'Atendimentos', 'Agendamentos', 'confirm'),
  permission('atendimentos.appointments.checkin', 'Fazer check-in', 'Atendimentos', 'Agendamentos', 'checkin'),
  permission('atendimentos.appointments.quick_create', 'Cadastro rapido de agendamento', 'Atendimentos', 'Agendamentos', 'quick_create'),

  permission('atendimentos.consultations.view', 'Ver consultas', 'Atendimentos', 'Consultas', 'view'),
  permission('atendimentos.consultations.create', 'Criar consultas', 'Atendimentos', 'Consultas', 'create'),
  permission('atendimentos.consultations.update', 'Editar consultas', 'Atendimentos', 'Consultas', 'update'),
  permission('atendimentos.consultations.delete', 'Excluir consultas', 'Atendimentos', 'Consultas', 'delete'),
  permission('atendimentos.consultations.finalize', 'Finalizar consultas', 'Atendimentos', 'Consultas', 'finalize'),
  permission('atendimentos.consultations.finalize_and_bill', 'Finalizar e faturar consultas', 'Atendimentos', 'Consultas', 'finalize_and_bill'),
  permission('atendimentos.consultations.approve_anamnesis', 'Aprovar anamnese', 'Atendimentos', 'Consultas', 'approve_anamnesis'),
  permission('atendimentos.consultations.ai', 'Usar IA em consultas', 'Atendimentos', 'Consultas', 'ai'),

  permission('atendimentos.consultation_attachments.view', 'Ver anexos clinicos', 'Atendimentos', 'Anexos clinicos', 'view'),
  permission('atendimentos.consultation_attachments.upload', 'Enviar anexos clinicos', 'Atendimentos', 'Anexos clinicos', 'upload'),
  permission('atendimentos.consultation_attachments.delete', 'Excluir anexos clinicos', 'Atendimentos', 'Anexos clinicos', 'delete'),
  permission('atendimentos.prescriptions.view', 'Ver prescricoes', 'Atendimentos', 'Prescricoes', 'view'),
  permission('atendimentos.prescriptions.create', 'Criar prescricoes', 'Atendimentos', 'Prescricoes', 'create'),
  permission('atendimentos.prescriptions.update', 'Editar prescricoes', 'Atendimentos', 'Prescricoes', 'update'),
  permission('atendimentos.prescriptions.print', 'Imprimir prescricoes', 'Atendimentos', 'Prescricoes', 'print'),
  permission('atendimentos.exam_requests.view', 'Ver pedidos de exame', 'Atendimentos', 'Pedidos de exame', 'view'),
  permission('atendimentos.exam_requests.create', 'Criar pedidos de exame', 'Atendimentos', 'Pedidos de exame', 'create'),
  permission('atendimentos.exam_requests.update', 'Editar pedidos de exame', 'Atendimentos', 'Pedidos de exame', 'update'),
  permission('atendimentos.exam_requests.print', 'Imprimir pedidos de exame', 'Atendimentos', 'Pedidos de exame', 'print'),
  permission('atendimentos.exam_results.view', 'Ver resultados de exame', 'Atendimentos', 'Resultados de exame', 'view'),
  permission('atendimentos.exam_results.create', 'Criar resultados de exame', 'Atendimentos', 'Resultados de exame', 'create'),
  permission('atendimentos.exam_results.update', 'Editar resultados de exame', 'Atendimentos', 'Resultados de exame', 'update'),
  permission('atendimentos.exam_results.upload', 'Enviar resultados de exame', 'Atendimentos', 'Resultados de exame', 'upload'),
  permission('atendimentos.inpatient_records.view', 'Ver internacoes', 'Atendimentos', 'Internacao', 'view'),
  permission('atendimentos.inpatient_records.create', 'Criar internacoes', 'Atendimentos', 'Internacao', 'create'),
  permission('atendimentos.inpatient_records.update', 'Editar internacoes', 'Atendimentos', 'Internacao', 'update'),
  permission('atendimentos.inpatient_records.discharge', 'Dar alta de internacao', 'Atendimentos', 'Internacao', 'discharge'),
  permission('atendimentos.inpatient_records.transfer', 'Transferir internacao', 'Atendimentos', 'Internacao', 'transfer'),
  permission('atendimentos.treatment_map.view', 'Ver mapa terapeutico', 'Atendimentos', 'Mapa terapeutico', 'view'),
  permission('atendimentos.treatment_map.create', 'Criar item do mapa terapeutico', 'Atendimentos', 'Mapa terapeutico', 'create'),
  permission('atendimentos.treatment_map.update', 'Editar mapa terapeutico', 'Atendimentos', 'Mapa terapeutico', 'update'),
  permission('atendimentos.treatment_map.execute', 'Executar mapa terapeutico', 'Atendimentos', 'Mapa terapeutico', 'execute'),
  permission('atendimentos.clinical_parameters.view', 'Ver parametros clinicos', 'Atendimentos', 'Parametros clinicos', 'view'),
  permission('atendimentos.clinical_parameters.create', 'Registrar parametros clinicos', 'Atendimentos', 'Parametros clinicos', 'create'),

  permission('clientes.clients.view', 'Ver clientes', 'Clientes', 'Clientes', 'view'),
  permission('clientes.clients.create', 'Criar clientes', 'Clientes', 'Clientes', 'create'),
  permission('clientes.clients.update', 'Editar clientes', 'Clientes', 'Clientes', 'update'),
  permission('clientes.clients.delete', 'Excluir clientes', 'Clientes', 'Clientes', 'delete'),
  permission('pets.pets.view', 'Ver pets', 'Pets', 'Pets', 'view'),
  permission('pets.pets.create', 'Criar pets', 'Pets', 'Pets', 'create'),
  permission('pets.pets.update', 'Editar pets', 'Pets', 'Pets', 'update'),
  permission('pets.pets.delete', 'Excluir pets', 'Pets', 'Pets', 'delete'),
  permission('pets.pet_files.upload', 'Enviar arquivos de pet', 'Pets', 'Arquivos de pet', 'upload'),
  permission('pets.pet_files.delete', 'Excluir arquivos de pet', 'Pets', 'Arquivos de pet', 'delete'),
  permission('pets.history.view', 'Ver historico do pet', 'Pets', 'Historico do pet', 'view'),

  permission('financeiro.sales.view', 'Ver vendas', 'Financeiro', 'Vendas', 'view'),
  permission('financeiro.sales.create', 'Criar vendas', 'Financeiro', 'Vendas', 'create'),
  permission('financeiro.sales.update', 'Editar vendas', 'Financeiro', 'Vendas', 'update'),
  permission('financeiro.sales.checkout', 'Receber venda', 'Financeiro', 'Vendas', 'checkout'),
  permission('financeiro.sales.cancel', 'Cancelar venda', 'Financeiro', 'Vendas', 'cancel'),
  permission('financeiro.sales.undo_checkout', 'Estornar recebimento de venda', 'Financeiro', 'Vendas', 'undo_checkout'),
  permission('financeiro.sales.receipt.print', 'Imprimir recibo de venda', 'Financeiro', 'Vendas', 'print'),
  permission('financeiro.payments.view', 'Ver pagamentos', 'Financeiro', 'Pagamentos', 'view'),
  permission('financeiro.payments.create', 'Criar pagamentos', 'Financeiro', 'Pagamentos', 'create'),
  permission('financeiro.payments.reverse', 'Estornar pagamentos', 'Financeiro', 'Pagamentos', 'reverse'),
  permission('financeiro.cash_registers.view', 'Ver caixa', 'Financeiro', 'Caixa', 'view'),
  permission('financeiro.cash_registers.open', 'Abrir caixa', 'Financeiro', 'Caixa', 'open'),
  permission('financeiro.cash_registers.close', 'Fechar caixa', 'Financeiro', 'Caixa', 'close'),
  permission('financeiro.cash_registers.withdraw', 'Registrar sangria', 'Financeiro', 'Caixa', 'withdraw'),
  permission('financeiro.cash_registers.current', 'Ver caixa atual', 'Financeiro', 'Caixa', 'current'),
  permission('financeiro.cash_registers.movements', 'Ver movimentacoes de caixa', 'Financeiro', 'Caixa', 'movements'),
  permission('financeiro.cash_registers.print_opening', 'Imprimir abertura de caixa', 'Financeiro', 'Caixa', 'print_opening'),
  permission('financeiro.cash_registers.print_closing', 'Imprimir fechamento de caixa', 'Financeiro', 'Caixa', 'print_closing'),
  permission('financeiro.cash_registers.manage_terminals', 'Gerenciar terminais de caixa', 'Financeiro', 'Caixa', 'manage_terminals'),
  permission('financeiro.cash_registers.manage_printers', 'Gerenciar impressoras de caixa', 'Financeiro', 'Caixa', 'manage_printers'),
  permission('financeiro.accounts_payable.view', 'Ver contas a pagar', 'Financeiro', 'Contas a pagar', 'view'),
  permission('financeiro.accounts_payable.create', 'Criar contas a pagar', 'Financeiro', 'Contas a pagar', 'create'),
  permission('financeiro.accounts_payable.update', 'Editar contas a pagar', 'Financeiro', 'Contas a pagar', 'update'),
  permission('financeiro.accounts_payable.pay', 'Pagar contas a pagar', 'Financeiro', 'Contas a pagar', 'pay'),
  permission('financeiro.accounts_payable.reverse', 'Estornar contas a pagar', 'Financeiro', 'Contas a pagar', 'reverse'),
  permission('financeiro.accounts_payable.delete', 'Excluir contas a pagar', 'Financeiro', 'Contas a pagar', 'delete'),
  permission('financeiro.accounts_receivable.view', 'Ver contas a receber', 'Financeiro', 'Contas a receber', 'view'),
  permission('financeiro.accounts_receivable.create', 'Criar contas a receber', 'Financeiro', 'Contas a receber', 'create'),
  permission('financeiro.accounts_receivable.update', 'Editar contas a receber', 'Financeiro', 'Contas a receber', 'update'),
  permission('financeiro.accounts_receivable.receive', 'Receber contas a receber', 'Financeiro', 'Contas a receber', 'receive'),
  permission('financeiro.accounts_receivable.reverse', 'Estornar contas a receber', 'Financeiro', 'Contas a receber', 'reverse'),
  permission('financeiro.accounts_receivable.delete', 'Excluir contas a receber', 'Financeiro', 'Contas a receber', 'delete'),
  permission('financeiro.commissions.view', 'Ver comissoes', 'Financeiro', 'Comissoes', 'view'),
  permission('financeiro.commissions.preview', 'Prever pagamento de comissoes', 'Financeiro', 'Comissoes', 'preview'),
  permission('financeiro.commissions.payout', 'Gerar pagamento de comissoes', 'Financeiro', 'Comissoes', 'payout'),
  permission('financeiro.commissions.pay', 'Pagar comissoes', 'Financeiro', 'Comissoes', 'pay'),
  permission('financeiro.commissions.undo_pay', 'Estornar pagamento de comissoes', 'Financeiro', 'Comissoes', 'undo_pay'),

  permission('fiscal.documents.view', 'Ver documentos fiscais', 'Fiscal', 'Documentos fiscais', 'view'),
  permission('fiscal.documents.issue', 'Emitir documentos fiscais', 'Fiscal', 'Documentos fiscais', 'issue'),
  permission('fiscal.documents.cancel', 'Cancelar documentos fiscais', 'Fiscal', 'Documentos fiscais', 'cancel'),
  permission('fiscal.documents.download', 'Baixar documentos fiscais', 'Fiscal', 'Documentos fiscais', 'download'),
  permission('fiscal.pending.view', 'Ver pendencias fiscais', 'Fiscal', 'Pendencias fiscais', 'view'),
  permission('fiscal.pending.resolve', 'Resolver pendencias fiscais', 'Fiscal', 'Pendencias fiscais', 'resolve'),
  permission('fiscal.settings.view', 'Ver configuracoes fiscais', 'Fiscal', 'Configuracoes fiscais', 'view'),
  permission('fiscal.settings.update', 'Editar configuracoes fiscais', 'Fiscal', 'Configuracoes fiscais', 'update'),
  permission('fiscal.profiles.create', 'Criar perfis fiscais', 'Fiscal', 'Perfis fiscais', 'create'),
  permission('fiscal.profiles.update', 'Editar perfis fiscais', 'Fiscal', 'Perfis fiscais', 'update'),
  permission('fiscal.certificates.upload', 'Enviar certificado fiscal', 'Fiscal', 'Certificados fiscais', 'upload'),
  permission('fiscal.certificates.update_password', 'Alterar senha de certificado fiscal', 'Fiscal', 'Certificados fiscais', 'update_password'),
  permission('fiscal.nfce_configs.update', 'Editar configuracoes NFC-e', 'Fiscal', 'NFC-e', 'update'),

  permission('estoque.balances.view', 'Ver saldos de estoque', 'Estoque', 'Saldos', 'view'),
  permission('estoque.movements.view', 'Ver movimentacoes de estoque', 'Estoque', 'Movimentacoes', 'view'),
  permission('estoque.movements.create', 'Criar movimentacoes de estoque', 'Estoque', 'Movimentacoes', 'create'),
  permission('estoque.movements.in', 'Registrar entrada de estoque', 'Estoque', 'Movimentacoes', 'in'),
  permission('estoque.movements.out', 'Registrar saida de estoque', 'Estoque', 'Movimentacoes', 'out'),
  permission('estoque.movements.adjust', 'Ajustar estoque', 'Estoque', 'Movimentacoes', 'adjust'),
  permission('estoque.batches.view', 'Ver lotes de estoque', 'Estoque', 'Lotes', 'view'),

  permission('relatorios.reports.view', 'Ver relatorios', 'Relatorios', 'Relatorios', 'view'),
  permission('relatorios.reports.generate', 'Gerar relatorios', 'Relatorios', 'Relatorios', 'generate'),
  permission('relatorios.reports.download', 'Baixar relatorios', 'Relatorios', 'Relatorios', 'download'),
  permission('relatorios.reports.history', 'Ver historico de relatorios', 'Relatorios', 'Relatorios', 'history'),

  permission('cadastros.users.view', 'Ver usuarios', 'Cadastros', 'Usuarios', 'view'),
  permission('cadastros.users.create', 'Criar usuarios', 'Cadastros', 'Usuarios', 'create'),
  permission('cadastros.users.update', 'Editar usuarios', 'Cadastros', 'Usuarios', 'update'),
  permission('cadastros.users.delete', 'Excluir usuarios', 'Cadastros', 'Usuarios', 'delete'),
  permission('cadastros.permissions.view', 'Ver permissoes', 'Cadastros', 'Permissoes', 'view'),
  permission('cadastros.permissions.manage', 'Gerenciar permissoes', 'Cadastros', 'Permissoes', 'manage'),

  permission('configuracoes.clinic.view', 'Ver configuracoes da clinica', 'Configuracoes', 'Clinica', 'view'),
  permission('configuracoes.clinic.update', 'Editar configuracoes da clinica', 'Configuracoes', 'Clinica', 'update'),
  permission('configuracoes.clinic.image.upload', 'Enviar imagem da clinica', 'Configuracoes', 'Clinica', 'upload'),
  permission('configuracoes.clinic.image.delete', 'Excluir imagem da clinica', 'Configuracoes', 'Clinica', 'delete'),
  permission('configuracoes.availability.view', 'Ver escalas e disponibilidade', 'Configuracoes', 'Escalas e disponibilidade', 'view'),
  permission('configuracoes.availability.update', 'Editar escalas e disponibilidade', 'Configuracoes', 'Escalas e disponibilidade', 'update'),

  permission('suporte.system.view', 'Ver area tecnica', 'Suporte', 'Sistema', 'view'),
  permission('suporte.audit_logs.view', 'Ver auditoria', 'Suporte', 'Auditoria', 'view'),
];

const crudResources = [
  ['cadastros.appointment_types', 'Tipos de agendamento'],
  ['cadastros.appointment_statuses', 'Status de agendamento'],
  ['cadastros.product_categories', 'Categorias de produto'],
  ['cadastros.suppliers', 'Fornecedores'],
  ['cadastros.boxes', 'Boxes de internacao'],
  ['cadastros.stock_locations', 'Locais de estoque'],
  ['cadastros.products', 'Produtos e servicos'],
  ['cadastros.procedures', 'Procedimentos medicos'],
  ['cadastros.exam_categories', 'Categorias de exame'],
  ['cadastros.exam_types', 'Tipos de exame'],
  ['cadastros.payment_methods', 'Formas de pagamento'],
  ['cadastros.species', 'Especies'],
  ['cadastros.breeds', 'Racas'],
] as const;

for (const [prefix, label] of crudResources) {
  PERMISSIONS.push(
    permission(`${prefix}.view`, `Ver ${label.toLowerCase()}`, 'Cadastros', label, 'view'),
    permission(`${prefix}.create`, `Criar ${label.toLowerCase()}`, 'Cadastros', label, 'create'),
    permission(`${prefix}.update`, `Editar ${label.toLowerCase()}`, 'Cadastros', label, 'update'),
    permission(`${prefix}.delete`, `Excluir ${label.toLowerCase()}`, 'Cadastros', label, 'delete'),
  );
}

export const DEFAULT_ROLE_CODES = {
  admin: 'ADMIN',
  manager: 'MANAGER',
  veterinarian: 'VETERINARIAN',
  vetLegacy: 'VET',
  vetAssistant: 'VET_ASSISTANT',
  receptionist: 'RECEPTIONIST',
  cashier: 'CASHIER',
  support: 'SUPPORT',
} as const;

const hasAnyPrefix = (code: string, prefixes: string[]) =>
  prefixes.some((prefix) => code.startsWith(prefix));

const byExact = (codes: string[]) => new Set(codes);

export const ROLE_PERMISSION_CODES: Record<string, string[]> = {
  ADMIN: PERMISSIONS.map((item) => item.code),
  MANAGER: PERMISSIONS.filter((item) => {
    if (item.code === 'cadastros.permissions.manage') return false;
    if (item.code === 'fiscal.certificates.upload') return false;
    if (item.code === 'fiscal.certificates.update_password') return false;
    if (item.code === 'cadastros.users.delete') return false;
    return !item.code.startsWith('suporte.');
  }).map((item) => item.code),
  VETERINARIAN: PERMISSIONS.filter((item) => {
    const exact = byExact([
      'dashboard.view',
      'atendimentos.appointments.view',
      'atendimentos.appointments.confirm',
      'atendimentos.consultations.view',
      'atendimentos.consultations.create',
      'atendimentos.consultations.update',
      'atendimentos.consultations.finalize',
      'atendimentos.consultations.approve_anamnesis',
      'atendimentos.consultations.ai',
      'atendimentos.consultation_attachments.view',
      'atendimentos.consultation_attachments.upload',
      'atendimentos.prescriptions.view',
      'atendimentos.prescriptions.create',
      'atendimentos.prescriptions.update',
      'atendimentos.prescriptions.print',
      'atendimentos.exam_requests.view',
      'atendimentos.exam_requests.create',
      'atendimentos.exam_requests.update',
      'atendimentos.exam_requests.print',
      'atendimentos.exam_results.view',
      'atendimentos.inpatient_records.view',
      'atendimentos.inpatient_records.create',
      'atendimentos.inpatient_records.update',
      'atendimentos.inpatient_records.discharge',
      'atendimentos.inpatient_records.transfer',
      'atendimentos.treatment_map.view',
      'atendimentos.treatment_map.create',
      'atendimentos.treatment_map.update',
      'atendimentos.treatment_map.execute',
      'atendimentos.clinical_parameters.view',
      'atendimentos.clinical_parameters.create',
      'clientes.clients.view',
      'pets.pets.view',
      'pets.pets.update',
      'pets.history.view',
      'estoque.balances.view',
    ]);
    return exact.has(item.code) || hasAnyPrefix(item.code, [
      'cadastros.products.view',
      'cadastros.procedures.view',
      'cadastros.exam_types.view',
      'cadastros.species.view',
      'cadastros.breeds.view',
    ]);
  }).map((item) => item.code),
  VET: [],
  VET_ASSISTANT: PERMISSIONS.filter((item) =>
    byExact([
      'dashboard.view',
      'atendimentos.appointments.view',
      'atendimentos.consultations.view',
      'atendimentos.consultation_attachments.view',
      'atendimentos.consultation_attachments.upload',
      'atendimentos.exam_requests.view',
      'atendimentos.exam_results.view',
      'atendimentos.exam_results.upload',
      'atendimentos.inpatient_records.view',
      'atendimentos.treatment_map.view',
      'atendimentos.treatment_map.execute',
      'atendimentos.clinical_parameters.view',
      'atendimentos.clinical_parameters.create',
      'clientes.clients.view',
      'pets.pets.view',
      'pets.history.view',
      'estoque.balances.view',
      'estoque.movements.view',
      'cadastros.appointment_types.view',
      'cadastros.appointment_statuses.view',
      'cadastros.boxes.view',
      'cadastros.products.view',
      'cadastros.procedures.view',
      'cadastros.exam_categories.view',
      'cadastros.exam_types.view',
      'cadastros.species.view',
      'cadastros.breeds.view',
      'cadastros.stock_locations.view',
    ]).has(item.code),
  ).map((item) => item.code),
  RECEPTIONIST: PERMISSIONS.filter((item) =>
    byExact([
      'dashboard.view',
      'atendimentos.appointments.view',
      'atendimentos.appointments.create',
      'atendimentos.appointments.update',
      'atendimentos.appointments.cancel',
      'atendimentos.appointments.confirm',
      'atendimentos.appointments.checkin',
      'atendimentos.appointments.quick_create',
      'atendimentos.consultations.view',
      'atendimentos.consultations.create',
      'clientes.clients.view',
      'clientes.clients.create',
      'clientes.clients.update',
      'pets.pets.view',
      'pets.pets.create',
      'pets.pets.update',
      'pets.pet_files.upload',
      'financeiro.sales.view',
      'financeiro.sales.create',
      'financeiro.sales.update',
      'financeiro.accounts_receivable.view',
      'financeiro.accounts_receivable.create',
      'financeiro.accounts_receivable.receive',
      'fiscal.documents.view',
      'cadastros.appointment_types.view',
      'cadastros.products.view',
      'cadastros.procedures.view',
      'cadastros.exam_types.view',
      'cadastros.species.view',
      'cadastros.breeds.view',
      'cadastros.payment_methods.view',
    ]).has(item.code),
  ).map((item) => item.code),
  CASHIER: PERMISSIONS.filter((item) =>
    byExact([
      'dashboard.view',
      'financeiro.sales.view',
      'financeiro.sales.create',
      'financeiro.sales.update',
      'financeiro.sales.checkout',
      'financeiro.sales.receipt.print',
      'financeiro.payments.view',
      'financeiro.payments.create',
      'financeiro.cash_registers.view',
      'financeiro.cash_registers.open',
      'financeiro.cash_registers.close',
      'financeiro.cash_registers.withdraw',
      'financeiro.cash_registers.current',
      'financeiro.cash_registers.movements',
      'financeiro.cash_registers.print_opening',
      'financeiro.cash_registers.print_closing',
      'financeiro.accounts_receivable.view',
      'financeiro.accounts_receivable.receive',
      'clientes.clients.view',
      'pets.pets.view',
      'cadastros.products.view',
      'cadastros.payment_methods.view',
      'fiscal.documents.view',
      'fiscal.documents.download',
      'fiscal.pending.view',
      'fiscal.pending.resolve',
    ]).has(item.code),
  ).map((item) => item.code),
  SUPPORT: PERMISSIONS.filter((item) =>
    byExact([
      'suporte.system.view',
      'suporte.audit_logs.view',
      'cadastros.users.view',
      'cadastros.permissions.view',
      'configuracoes.clinic.view',
      'fiscal.settings.view',
      'fiscal.documents.view',
      'fiscal.pending.view',
    ]).has(item.code) || (item.module === 'Cadastros' && item.action === 'view'),
  ).map((item) => item.code),
};

ROLE_PERMISSION_CODES.VET = ROLE_PERMISSION_CODES.VETERINARIAN;
